jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps:
      - uses: actions/checkout@master

      - name: Deploy org
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: 
          BRANCH: main
          FOLDER: dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
name: Sync To Gitee
on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        with:
          source-repo: "git@gitee.com:Ark-survey/Ark-survey-backend.git"
          destination-repo: "git@gitee.com:timothybu/Ark-survey-backend.git"